# Array
- La estructura central de NumPy
- Representa los datos de manera estructurada
- Indexado
- Accesoa uno o mucho elementos

In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Con np convertimos una lista en un array

In [3]:
arr = np.array(lista)


In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[6]+arr[4]

12

In [13]:
#Intervalos de indices 
arr[3:7:2]

array([4, 6])

In [14]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
mat = np.array(matriz)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
mat[1:,0:1]

array([[4],
       [7]])

Conversion de una lista a un array
primeramente importamos la libreria numpy
luego realizamos la conversion
 --> para saber el tipo de datos usamos type()
 #array.dtype
 -->podemos definir el tipo de dato con lo que queremos trabajar para tener mejor precisión
 lo cual se realiza de la seguiente manera
 arr = np.array([1,2,3,4,5], dtype=np.int32)
 en este caso  espesificamos el tipo de int32